create table if not exists public.pending_receipts (
  id bigint generated by default as identity primary key,
  vessel_id text,
  source text,
  receipt_type text,
  email_from text,
  email_subject text,
  email_body text,
  extracted_data jsonb,
  attachment_url text,
  status text not null default 'pending',
  received_at timestamptz not null default now(),
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists pending_receipts_status_idx on public.pending_receipts (status);
create index if not exists pending_receipts_created_at_idx on public.pending_receipts (created_at desc);

-- Keep behavior aligned with existing app tables that are queried by anon key.
alter table public.pending_receipts disable row level security;
