create table if not exists public.receipt_webhook_events (
  id bigint generated by default as identity primary key,
  content_type text,
  parse_mode text,
  email_from text,
  email_subject text,
  status text not null,
  pending_receipt_id bigint,
  error_message text,
  payload_summary jsonb,
  created_at timestamptz not null default now()
);

create index if not exists receipt_webhook_events_created_at_idx
  on public.receipt_webhook_events (created_at desc);

create index if not exists receipt_webhook_events_status_idx
  on public.receipt_webhook_events (status);

alter table public.receipt_webhook_events disable row level security;
